[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions/"
  
[dev]
  command = "svelte-kit dev"
  functions = "netlify/functions/"
[functions]
    directory = "netlify/functions"
    node_bundler = "esbuild"
    external_node_modules = ["@sveltejs/kit/ssr"]